### ISSUE TITLE
Broken on Windows

### ISSUE THREAD

**Issue by gfody** [fabiospampinato/vscode-browser-refresh#3]
**edit**: just noticed that the description says macOS only -- feel free to close

Just installed VSCode 1.38.0 (default windows install) and vscode-browser-refresh 1.1.5 from the marketplace and I get this error when pressing ctrl+r
(I tried re-installing VSCode w/o spaces in the path but got the same error)
```
[exthost] [error] Error: write EPIPE
	at afterWriteDispatched (internal/stream_base_commons.js:78:25)
	at writeGeneric (internal/stream_base_commons.js:73:3)
	at Socket._writeGeneric (net.js:713:5)
	at Socket._write (net.js:725:8)
	at doWrite (_stream_writable.js:410:12)
	at writeOrBuffer (_stream_writable.js:394:5)
	at Socket.Writable.write (_stream_writable.js:294:11)
	at i (c:\Users\Gordy\.vscode\extensions\fabiospampinato.vscode-browser-refresh-1.1.5\out\extension.js:1:3276)
	at Object.module.exports.t.execString (c:\Users\Gordy\.vscode\extensions\fabiospampinato.vscode-browser-refresh-1.1.5\out\extension.js:1:3513)
	at o (c:\Users\Gordy\.vscode\extensions\fabiospampinato.vscode-browser-refresh-1.1.5\out\extension.js:1:4013)
	at module.exports.o.initCommands.t.forEach.u.commands.registerCommand (c:\Users\Gordy\.vscode\extensions\fabiospampinato.vscode-browser-refresh-1.1.5\out\extension.js:1:1100)
	at _executeContributedCommand (c:\Users\Gordy\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:518:163)
	at _.$executeContributedCommand (c:\Users\Gordy\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:518:538)
	at d._doInvokeHandler (c:\Users\Gordy\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:623:396)
	at d._invokeHandler (c:\Users\Gordy\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:623:88)
	at d._receiveRequest (c:\Users\Gordy\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:621:783)
	at d._receiveOneMessage (c:\Users\Gordy\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:620:605)
	at define.constructor._protocol.onMessage.e (c:\Users\Gordy\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:618:791)
	at u.fire (c:\Users\Gordy\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:50:207)
	at v.fire (c:\Users\Gordy\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:186:579)
	at i.constructor.e.onMessage.e (c:\Users\Gordy\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:783:484)
	at u.fire (c:\Users\Gordy\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:50:207)
	at v.fire (c:\Users\Gordy\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:186:579)
	at x._receiveMessage (c:\Users\Gordy\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:191:17)
	at define.constructor._socketDisposables.push._socketReader.onMessage.e (c:\Users\Gordy\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:188:116)
	at u.fire (c:\Users\Gordy\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:50:207)
	at f.acceptChunk (c:\Users\Gordy\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:184:17)
	at define.constructor._register._socket.onData.e (c:\Users\Gordy\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:183:372)
	at Socket.t (c:\Users\Gordy\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:192:491)
	at Socket.emit (events.js:182:13)
	at addChunk (_stream_readable.js:283:12)
	at readableAddChunk (_stream_readable.js:264:11)
	at Socket.Readable.push (_stream_readable.js:219:10)
	at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17) browserRefresh.refresh
```

**Comment by fabiospampinato** [comment]
This is mentioned in the very second paragraph in the readme:

> It's currently implemented using an AppleScript, which makes this extension macOS only. If you know how to do the same on Windows or Linux please submit a PR.

**Comment by Gennady-G** [comment]
Plugin looks great. Unfortunately mac-os only..

@gfody , any good news? Have You found any way to do the same on windows?
